### ISSUE TITLE
Release tag

### ISSUE THREAD

**Issue by katyukha** [BindBC/bindbc-common#1]
Hi,

I have tried to use master version of this lib in my project to dynamically load Python and it works well.

So, the question: is it stable enough to make a release tag for this version?

Thanks a lot for this amaizing library that make dynamic loading of C libraries so easy)

**Comment by ichordev** [comment]
I’m really glad to hear that you’ve gotten some use out of this library! I remember being afraid of other people using 0.1.0 because it was so messy, but 0.1.1 was meant to fix that.
If my memory is correct I *felt like* 0.1.1 was done, but I hadn’t conducted enough testing to be 100% sure.
If you’d like, I can tag a pre-release of 0.1.1 for you so that you don’t have to worry about me breaking `~master` with future commits.

**Comment by katyukha** [comment]
Thanks for explanation.

I think it will be enough for me to use master branch for some time: In next 1-2 weeks i plan to migrate my [Zipper](https://github.com/katyukha/Zipper) library to use bind-bc for static and dynamic bindings, it has better test coverage thus thus i will be able to test more functionality of this lib. When i will finish that, i will add comment about results.

Currently, i use bindbc [here](https://github.com/katyukha/Odood/blob/7cfe1fa61825ded4beb58b831d4739422ef39076/subpackages/utils/source/odood/utils/tipy/python.d). In Odood, i use only dynamic bindings, but in Zipper, i will try to use both static and dynamic bindings with different dub configuration.

Additionally, it would be nice to have more documentation on how to use this library.

Thanks a lot.

**Comment by ichordev** [comment]
> Additionally, it would be nice to have more documentation on how to use this library.

I'm bad at writing documentation, but I'll try.

> Thanks a lot.

Not a problem!

**Comment by katyukha** [comment]
Hi,

I have tested it on Zipper and it seems that it works fine on linux for static and dynamic builds.
I did not have tested it on windows and mac.

**Comment by ichordev** [comment]
That’s great to hear!
Part of the testing that I still need to do is making sure that `0.1.1` is still fully backwards compatible with all the BindBC libraries that use `0.1.0` so that I know for sure that I don’t need to increment the minor version number of every dependant BindBC library. (You have probably seen some of the crazy trickery I did to make this possible, and I should be able to use a similar technique again in case I have to remodel  the API at all)

**Comment by ichordev** [comment]
Closing since v1.0.0 has been officially released.
